! File shared.f90
SUBROUTINE MySuba(x) BIND(C,NAME="MySub1")
   USE ISO_C_BINDING
   REAL(C_DOUBLE), VALUE :: x
   WRITE(*,*) "MySub1: x=",x
END SUBROUTINE   
SUBROUTINE MySubb(x) BIND(C,NAME="MySub2")
   USE ISO_C_BINDING
   REAL(C_DOUBLE), VALUE :: x
   WRITE(*,*) "MySub2: x=",x
END SUBROUTINE   
SUBROUTINE MySubc(x) BIND(C,NAME="MySub3")
   USE ISO_C_BINDING
   REAL(C_DOUBLE), VALUE :: x
   WRITE(*,*) "MySub3: x=",x
END SUBROUTINE   

