! File shared.f90
SUBROUTINE MySub(x) BIND(C,NAME="MySub")
   USE ISO_C_BINDING
   REAL(C_DOUBLE), VALUE :: x
   WRITE(*,*) "MySub: x=",x
END SUBROUTINE   
SUBROUTINE MySub2(x) BIND(C,NAME="MySub2")
   USE ISO_C_BINDING
   REAL(C_DOUBLE), VALUE :: x
   WRITE(*,*) "MySub2: x=",x
END SUBROUTINE   
SUBROUTINE MySub3(x) BIND(C,NAME="MySub3")
   USE ISO_C_BINDING
   REAL(C_DOUBLE), VALUE :: x
   WRITE(*,*) "MySub3: x=",x
END SUBROUTINE   

